name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: Run deployment
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.KEY_PASSWORD }}
      run: sbt publishSigned;moveBundle;sonatypeBundleRelease;deleteBundle
