name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: olafurpg/setup-scala@v10
    - name: release
      run: sbt ci-release
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.KEY_PASSWORD }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}      
    - name: Run deployment
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.KEY_PASSWORD }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: sbt publishSigned; sbt moveBundle; sbt sonatypeBundleRelease;sbt deleteBundle
        
        
        
